export type LessonReference = {
  label: string;
  url: string;
  note: string;
};

export type LessonGuide = {
  todaysIdea: string;
  whyExists: string;
  howUsed: string;
  whyCare: string;
  realExamples: string[];
  keyWords: Array<{ term: string; meaning: string }>;
  explainPrompt: string;
  ownWords: string[];
  newsTerms: string[];
  prerequisites: number[];
  references?: LessonReference[];
};

export const LESSON_GUIDES: Record<number, LessonGuide> = {
  1: {
    todaysIdea: "AIは一つの魔法ではなく、入力から目的に合う出力を作る技術の集合。",
    whyExists: "人が規則をすべて書き切れない認識・予測・生成を、データと計算で扱うため。",
    howUsed: "検索順位、画像認識、需要予測、ChatGPTの文章生成まで、異なる目的に別々のAIが使われている。",
    whyCare: "新サービスを見るとき、入力・出力・学習方法・評価基準へ分解できれば、宣伝文句と実力を分けて考えられる。",
    realExamples: ["ChatGPTは文章を入れて文章や操作結果を返す生成AI。", "病変検出AIや需要予測AIは、生成を主目的にしないAI。"],
    keyWords: [{ term: "AI", meaning: "知的に見える処理を実現する技術群の総称" }, { term: "機械学習", meaning: "データから規則を調整するAIの方法" }, { term: "生成AI", meaning: "文章・画像・音など新しい出力を作るAI" }],
    explainPrompt: "『AIと生成AIは同じもの？』と聞かれたら、違いを30秒で説明できますか？",
    ownWords: ["AIは大きな総称", "生成AIはその中の『作る』領域", "何を入れ、何を出す仕組みかを見る"],
    newsTerms: ["artificial intelligence", "AI system", "generative AI"],
    prerequisites: [],
  },
  2: {
    todaysIdea: "機械学習は例から規則を調整し、深層学習は特徴の作り方まで学ぶ。",
    whyExists: "現実の例外を人が条件分岐で列挙するより、多数の例から判断境界を学ばせた方が強い問題があるため。",
    howUsed: "表形式の予測には従来型機械学習、画像・音声・言語のような複雑な入力には深層学習がよく使われる。",
    whyCare: "『最新の巨大モデルが常に最適』ではない。品質、説明しやすさ、速度、費用、データ量で選ぶ。",
    realExamples: ["迷惑メール判定は、正常・迷惑メールの例から境界を学べる。", "画像生成やLLMの現在の中心は深層学習。"],
    keyWords: [{ term: "機械学習", meaning: "例から予測規則を調整する方法" }, { term: "Deep Learning", meaning: "多層ニューラルネットワークを使う機械学習" }, { term: "特徴量", meaning: "判断に役立つ入力の表現" }],
    explainPrompt: "機械学習とDeep Learningの関係を、優劣ではなく範囲の違いとして説明してください。",
    ownWords: ["Deep Learningは機械学習の一部", "特徴表現まで学びやすい", "小さい問題では従来手法も現役"],
    newsTerms: ["machine learning", "deep learning", "foundation model"],
    prerequisites: [1],
  },
  3: {
    todaysIdea: "ニューラルネットワークは、学習で調整される大量の数値変換を層状につないだもの。",
    whyExists: "画像や言語にある複雑で曲がった関係を、固定ルールではなくデータから表現するため。",
    howUsed: "画像の画素や文章のTokenを数値へ変え、層ごとの計算で分類・予測・生成に必要な表現へ変換する。",
    whyCare: "モデルの『知識』は文章の本棚ではなく、多数の重みに分散したパターンだと分かると、忘却や誤答も理解しやすい。",
    realExamples: ["LLMではTransformerの層がTokenの関係を何段も変換する。", "画像モデルでは低い層から形や構図に関わる表現が形成される。"],
    keyWords: [{ term: "Parameter", meaning: "学習で調整される内部の数値" }, { term: "Weight", meaning: "入力の影響の強さを決める代表的なParameter" }, { term: "Layer", meaning: "数値変換を行う一段" }],
    explainPrompt: "『モデルの中に文章が保存されているの？』へ、重みという言葉を使って答えてください。",
    ownWords: ["中身は大量の数値", "学習で重みを調整", "知識は分散したパターン"],
    newsTerms: ["parameter count", "neural network", "model weights"],
    prerequisites: [1, 2],
  },
  4: {
    todaysIdea: "Trainingは、間違いを数値化してParameterを少しずつ直す工程。",
    whyExists: "望ましい出力へ近づけるには、良し悪しを測り、どの数値をどちらへ動かすか決める必要があるため。",
    howUsed: "事前学習で広いパターンを学び、その後の調整で指示への従い方や安全性を改善する。",
    whyCare: "訓練成績と初見性能は別。学習データ、追加学習、評価データの違いを読めるとモデル発表を誤解しにくい。",
    realExamples: ["LLMは次のToken予測の誤差を減らす事前学習を行う。", "製品化前には人の好みや安全方針に合わせた追加調整も行われる。"],
    keyWords: [{ term: "Training", meaning: "データからParameterを調整する工程" }, { term: "Loss", meaning: "望ましい出力とのずれを表す数値" }, { term: "Generalization", meaning: "未見データにも対応できること" }, { term: "Overfitting", meaning: "訓練例へ合わせすぎること" }],
    explainPrompt: "『学習データで100点なら最高のAI？』という問いへ答えてください。",
    ownWords: ["誤差を測る", "誤差が減る方向へ数値を更新", "初見問題で測らないと実力は分からない"],
    newsTerms: ["training run", "pretraining", "post-training", "training data"],
    prerequisites: [2, 3],
  },
  5: {
    todaysIdea: "生成AIは、学んだデータの構造を使って新しい候補を確率的に作る。",
    whyExists: "分類や予測だけでなく、文章・画像・音・動画そのものを人の指示に合わせて作るため。",
    howUsed: "LLMは次のToken、画像・動画モデルは画面や時間方向の構造、音楽モデルは音の並びを生成する。",
    whyCare: "自然さ、独自性、事実性、権利上の安全は別々に確認する必要がある。生成できることと公開できることも別。",
    realExamples: ["ChatGPTは文章、Midjourneyは画像、Sunoは楽曲を生成する。", "同じPromptでもSamplingのため出力が変わることがある。"],
    keyWords: [{ term: "生成AI", meaning: "新しいデータを作るAI" }, { term: "確率分布", meaning: "どんな出力がどれくらい起きやすいかの表現" }, { term: "Sampling", meaning: "確率から実際の出力候補を選ぶ処理" }],
    explainPrompt: "生成AIの『創作』と、完全な無からの創作が同じではない理由を説明してください。",
    ownWords: ["学んだ構造を基に作る", "出力には揺らぎがある", "自然さと正しさは別"],
    newsTerms: ["generative model", "sampling", "synthetic media"],
    prerequisites: [1, 4],
  },
  6: {
    todaysIdea: "LLMは、文脈から次のTokenを予測する大規模な言語モデル。",
    whyExists: "言語の規則、知識、文脈の関係を一つずつ人が書かず、大量の文章から学ぶため。",
    howUsed: "ChatGPT、Gemini、Claudeなどの中核として、文章作成、要約、コード、検索補助、Tool操作に使われる。",
    whyCare: "流暢な応答は事実保証ではない。モデル、製品UI、検索、Memory、Toolを分けて見ることが重要。",
    realExamples: ["ChatGPTは製品名で、その内部モデルや接続Toolは状況により変わる。", "ClaudeやGeminiもLLMを中心に複数機能を組み合わせた製品。"],
    keyWords: [{ term: "LLM", meaning: "Large Language Modelの略" }, { term: "Pretraining", meaning: "広いデータから基礎能力を作る学習" }, { term: "Post-training", meaning: "指示追従や安全性などを後から調整する工程" }],
    explainPrompt: "LLMを『巨大な検索データベース』と呼ぶと不正確な理由は？",
    ownWords: ["次のTokenを予測する", "大規模学習で言語パターンを得る", "製品全体とモデル単体を分ける"],
    newsTerms: ["LLM", "language model", "foundation model", "post-training"],
    prerequisites: [3, 4, 5],
  },
  7: {
    todaysIdea: "Tokenは、LLMが文章を計算するために区切った単位。文字数や単語数とは一致しない。",
    whyExists: "文章をそのまま計算できないため、有限の単位へ分けてIDと数値表現へ変換する必要がある。",
    howUsed: "入力も出力もTokenとして処理され、API料金、速度、Context Windowの使用量へ直接影響する。",
    whyCare: "長い資料や日本語の料金を見積もるとき、文字数だけでは判断できない。モデルごとにTokenizerも異なる。",
    realExamples: ["同じ文でも英語と日本語、モデルのTokenizerでToken数が変わる。", "APIは入力Tokenと出力Tokenを別単価で計算することが多い。"],
    keyWords: [{ term: "Token", meaning: "モデルが文章を扱う分割単位" }, { term: "Tokenizer", meaning: "文章をToken IDへ分ける仕組み" }, { term: "Vocabulary", meaning: "モデルが使えるTokenの一覧" }],
    explainPrompt: "『1 Tokenは1単語？』と聞かれたら、費用との関係も含めて答えてください。",
    ownWords: ["モデル用の文章の区切り", "単語・文字とは固定対応しない", "料金とContext量に効く"],
    newsTerms: ["token", "tokenizer", "tokens per second", "input tokens"],
    prerequisites: [6],
  },
  8: {
    todaysIdea: "Transformerは、Attentionで文脈内の関係を重み付けして処理する構造。",
    whyExists: "離れたToken同士の関係を扱い、大量データを並列に学習しやすくするため。",
    howUsed: "現在のLLMの中心構造で、画像や音声を扱うモデルにもTransformer系の設計が広く使われる。",
    whyCare: "Attentionを『重要部分だけ見る意識』ではなく、Token間の参照度を計算する仕組みとして理解すると誇張を避けられる。",
    realExamples: ["『彼女が店で買った本。それは…』の『それ』が何を指すかを文脈から結び付ける。", "GeminiやClaudeなどモデル名は違ってもTransformer系の土台を共有する。"],
    keyWords: [{ term: "Transformer", meaning: "Attentionを中心にしたニューラルネットワーク構造" }, { term: "Attention", meaning: "Token同士をどれだけ参照するか計算する仕組み" }, { term: "Position", meaning: "Tokenの順序情報" }],
    explainPrompt: "Transformerが2017年以降のLLM拡大に向いていた理由を一つ説明してください。",
    ownWords: ["Token同士の関係を計算", "離れた文脈も結び付ける", "大規模学習へ拡張しやすかった"],
    newsTerms: ["Transformer", "attention mechanism", "architecture"],
    prerequisites: [3, 7],
    references: [{ label: "Attention Is All You Need", url: "https://arxiv.org/abs/1706.03762", note: "Transformerを提案した2017年の論文" }],
  },
  9: {
    todaysIdea: "Context Windowは、モデルが一回の処理で参照できるToken量の上限。",
    whyExists: "計算量とメモリには限界があり、会話・資料・出力を無制限に同時参照できないため。",
    howUsed: "会話履歴、System Prompt、添付資料、Tool結果、生成途中の出力が同じContextを使う。",
    whyCare: "上限が大きくても全位置を同じ精度で使えるとは限らない。必要情報を選ぶ設計と評価が要る。",
    realExamples: ["長いPDFを複数入れると、回答用のToken余地が減る。", "Agentでは過去ログを全部入れず、要約や検索で必要部分だけ戻す。"],
    keyWords: [{ term: "Context Window", meaning: "一回で参照できるToken範囲" }, { term: "Input Token", meaning: "モデルへ渡す側のToken" }, { term: "Output Token", meaning: "モデルが生成する側のToken" }],
    explainPrompt: "Context Windowが100万Tokenなら、長文理解が必ず完璧と言えないのはなぜ？",
    ownWords: ["一度に見える範囲", "会話・資料・出力で共有", "広さと使いこなす精度は別"],
    newsTerms: ["context window", "long context", "million tokens"],
    prerequisites: [7, 8],
  },
  10: {
    todaysIdea: "Embeddingは、意味の近さを計算できる数値の座標へ変える技術。",
    whyExists: "言葉が完全一致しなくても、意味が近い文章・画像・商品を探せるようにするため。",
    howUsed: "文章検索、推薦、重複判定、RAGの資料検索で使い、Vector Databaseが多数の座標を高速に探す。",
    whyCare: "RAGの品質はLLMだけでなく、何をどうEmbedding化し、どの単位で検索するかに大きく左右される。",
    realExamples: ["『腎代替療法』で検索して『透析』を含む文書を見つける。", "作品説明の意味が近い画像群をまとめる。"],
    keyWords: [{ term: "Embedding", meaning: "意味を表す数値ベクトル" }, { term: "Vector", meaning: "複数の数値を並べた座標" }, { term: "Vector Database", meaning: "近いVectorを高速検索する保存先" }],
    explainPrompt: "通常のキーワード検索とEmbedding検索の違いを、例を一つ使って説明してください。",
    ownWords: ["意味を座標にする", "近い意味を距離で探す", "RAGの検索部分を支える"],
    newsTerms: ["embedding", "vector database", "semantic search"],
    prerequisites: [3, 7],
  },
  11: {
    todaysIdea: "Inferenceは、学習済みモデルへ入力し、実際の回答を一Tokenずつ作る処理。",
    whyExists: "Trainingで作った能力を、利用者の新しい入力へ適用するため。",
    howUsed: "入力をToken化し、EmbeddingとTransformerを通し、次Tokenの候補確率から選ぶ工程を繰り返す。",
    whyCare: "モデルの速度、待ち時間、出力Token単価、Reasoning量はすべて実利用のInference設計に関係する。",
    realExamples: ["ストリーミング表示は、生成済みTokenを順に画面へ送っている。", "高速モデルと深く考えるモデルでは、同じ質問でも時間と費用が違う。"],
    keyWords: [{ term: "Inference", meaning: "学習済みモデルで出力を得る処理" }, { term: "Logits", meaning: "次Token候補の選ばれやすさを表す値" }, { term: "Temperature", meaning: "出力候補のばらつきを調整する設定" }],
    explainPrompt: "TrainingとInferenceの違いを、普段ChatGPTを使う場面に結び付けて説明してください。",
    ownWords: ["Training後のモデルを使う工程", "次Tokenを繰り返し生成", "速度・費用・待ち時間に直結"],
    newsTerms: ["inference", "latency", "tokens per second", "serving"],
    prerequisites: [4, 7, 8],
  },
  12: {
    todaysIdea: "Hallucinationは、もっともらしいが根拠のない出力が生まれる現象。",
    whyExists: "LLMは事実データベースの検索ではなく、文脈に続くTokenを生成するため、流暢さと正しさが分離する。",
    howUsed: "検索・RAG・計算Tool・引用・出力後検証で減らすが、重要情報では最終確認を残す。",
    whyCare: "医療、法律、契約、出典、最新情報では『自信ありげ』を根拠にしない運用が必須。",
    realExamples: ["存在しない論文名やURLを自然に作ることがある。", "検索結果を引用していても、その引用が主張を本当に支えるか確認する。"],
    keyWords: [{ term: "Hallucination", meaning: "根拠のない内容をもっともらしく生成すること" }, { term: "Grounding", meaning: "回答を確認可能な情報へ結び付けること" }, { term: "Citation", meaning: "主張を支える参照元" }],
    explainPrompt: "LLMがHallucinationする理由と、実務での対策を一つずつ説明してください。",
    ownWords: ["流暢さは正しさではない", "生成の仕組みから起きる", "根拠へ接続して検証する"],
    newsTerms: ["hallucination", "grounding", "factuality", "citation"],
    prerequisites: [6, 11],
  },
  13: {
    todaysIdea: "Promptは魔法の言い回しではなく、目的・材料・制約・評価基準を渡す設計。",
    whyExists: "同じモデルでも、何を達成し何を避けるかが曖昧なら、望ましい出力を安定して選べないため。",
    howUsed: "System指示、利用者の依頼、例示、添付資料、出力形式を組み合わせてタスクを定義する。",
    whyCare: "長い美辞麗句より、必要情報と成功条件が具体的なPromptの方が再利用・評価・修正しやすい。",
    realExamples: ["『格好良く』ではなく、用途・対象・長さ・禁止事項・合格例を渡す。", "画像生成では被写体、構図、光、媒体、避けたい要素を分ける。"],
    keyWords: [{ term: "Prompt", meaning: "モデルへ渡す入力・指示" }, { term: "System Instruction", meaning: "会話全体の役割や制約を定める上位指示" }, { term: "Few-shot", meaning: "望ましい入出力例を少数示す方法" }],
    explainPrompt: "良いPromptに必要な要素を、実際の制作依頼を例に説明してください。",
    ownWords: ["目的を明確にする", "必要な材料と制約を渡す", "良い出力の基準を示す"],
    newsTerms: ["prompting", "instruction following", "system prompt"],
    prerequisites: [6, 9, 12],
  },
  14: {
    todaysIdea: "Reasoningモデルは、難しい問題へInference時の追加計算を使うモデル。",
    whyExists: "即答では崩れやすい多段の計画、数学、コード、検証を、途中の計算と見直しで改善するため。",
    howUsed: "問題の難しさに応じてReasoning effortや計算時間を変え、軽い仕事は高速モデルへ振り分ける。",
    whyCare: "『長く考えたから正しい』ではない。品質向上と待ち時間・費用の交換条件をタスク別に評価する。",
    realExamples: ["複数ファイルの改修計画は深いReasoning、短い分類は高速モデルが向く。", "Agentは計画だけでなく各操作後の確認にも推論を使う。"],
    keyWords: [{ term: "Reasoning", meaning: "複数段の問題解決へ追加計算を使うこと" }, { term: "Reasoning effort", meaning: "推論へ割く計算量の目安" }, { term: "Routing", meaning: "タスクに応じてモデルや処理を振り分けること" }],
    explainPrompt: "Reasoningモデルを全タスクへ使わない方がよい理由を説明してください。",
    ownWords: ["難問へ追加計算", "正解保証ではない", "品質と速度・費用を使い分ける"],
    newsTerms: ["reasoning model", "test-time compute", "reasoning effort"],
    prerequisites: [11, 12, 13],
  },
  15: {
    todaysIdea: "Multimodal AIは、文章・画像・音声・動画など複数形式を同じ仕事の中で扱う。",
    whyExists: "現実の仕事は文章だけで完結せず、画面、声、映像、図表を一緒に理解・生成する必要があるため。",
    howUsed: "画像を見て答える、音声で会話する、動画を解析する、画面を見ながらPCを操作する機能へ使われる。",
    whyCare: "入力対応と出力対応は別。画像を理解できても画像を生成できるとは限らず、品質評価も形式ごとに必要。",
    realExamples: ["GeminiやChatGPTへ画像を渡して内容を質問する。", "映像・音声・字幕を合わせて編集候補を作る。"],
    keyWords: [{ term: "Multimodal", meaning: "複数の情報形式を扱うこと" }, { term: "Modality", meaning: "文章、画像、音声など情報の形式" }, { term: "Vision-Language", meaning: "画像と文章を結び付けて扱うモデル" }],
    explainPrompt: "『画像対応モデル』という発表で、入力と出力を分けて確認すべき理由は？",
    ownWords: ["複数の情報形式を扱う", "理解と生成は別能力", "形式ごとの性能を見る"],
    newsTerms: ["multimodal", "omnimodal", "vision-language", "native audio"],
    prerequisites: [5, 6, 8],
  },
  16: {
    todaysIdea: "画像生成AIは、Promptだけでなく参照画像・構図・編集条件で結果を制御する仕組み。",
    whyExists: "言葉で指定した視覚表現を作り、探索・修正・量産を短い反復で行うため。",
    howUsed: "Text-to-image、Image-to-image、部分修正、拡張、キャラクター参照、スタイル・構図制御に使う。",
    whyCare: "制作では一枚の偶然の当たりより、一貫性、修正可能性、解像度、商用条件、来歴表示が重要。",
    realExamples: ["Midjourneyは生成と参照制御、Adobe Fireflyは制作ツール内編集との接続が強い。", "Seedreamや各社画像モデルも生成から編集・一貫性へ競争軸を広げている。"],
    keyWords: [{ term: "Diffusion", meaning: "ノイズから段階的に画像を形成する代表的手法" }, { term: "Latent", meaning: "画像を圧縮して扱う内部表現" }, { term: "Reference", meaning: "人物・構図・見た目の条件に使う参照入力" }],
    explainPrompt: "画像生成モデルの進歩を、単なる画質以外の軸で三つ説明してください。",
    ownWords: ["ノイズや内部表現から画像化", "参照と編集で制御", "一貫性・権利・工程接続も性能"],
    newsTerms: ["image generation", "diffusion", "image editing", "character consistency", "Midjourney", "Firefly", "Seedream"],
    prerequisites: [5, 15],
    references: [{ label: "Midjourney Version", url: "https://docs.midjourney.com/hc/en-us/articles/32199405667853-Version", note: "現行Versionと機能は公式資料で確認" }],
  },
  17: {
    todaysIdea: "動画生成AIの難所は、各フレームの美しさより時間をまたぐ一貫性と演出制御。",
    whyExists: "文章や静止画から動き、カメラ、演技、時間変化を持つ映像を作り、制作工程を短縮するため。",
    howUsed: "Text-to-video、Image-to-video、参照動画編集、キャラクター維持、音声同期、ショット延長に使う。",
    whyCare: "モデル比較では尺、破綻率、指示追従、開始・終了フレーム、音声、再編集性、生成費用を見る。",
    realExamples: ["KlingやSeedanceは参照・カメラ・複数ショット制御を拡張。", "Runwayは生成モデルに加え、編集環境や複数モデルの使い分けを製品化している。"],
    keyWords: [{ term: "Temporal consistency", meaning: "時間が進んでも人物や物体が不自然に変わらない性質" }, { term: "Image-to-video", meaning: "静止画を出発点に動画化する方法" }, { term: "Shot", meaning: "一続きのカメラ撮影単位" }],
    explainPrompt: "動画AIの『高画質』だけでは実制作性能が分からない理由を説明してください。",
    ownWords: ["時間方向の整合性が難しい", "動きとカメラを条件指定", "編集しやすさと費用まで見る"],
    newsTerms: ["video generation", "world model", "temporal consistency", "Kling", "Seedance", "Hailuo", "Runway"],
    prerequisites: [15, 16],
    references: [{ label: "ByteDance Seedance", url: "https://seed.bytedance.com/en/models", note: "Seedanceを含む公式モデル一覧" }, { label: "Runway News", url: "https://runwayml.com/news", note: "生成・編集製品の公式発表" }],
  },
  18: {
    todaysIdea: "音声生成と音楽生成は別領域。声、効果音、歌、曲の構造で評価軸が変わる。",
    whyExists: "文章から自然な発話を作る、声質を変える、楽曲や素材を生成するなど異なる音の仕事を支えるため。",
    howUsed: "TTS、Voice conversion、Dubbing、効果音、歌詞付き楽曲、Stem分離、DAW内編集に使う。",
    whyCare: "声の同意・権利、楽曲の商用条件、似すぎ問題、編集可能なStem、発音や歌唱の制御を分けて確認する。",
    realExamples: ["ElevenLabsは音声合成・Dubbing、Sunoは曲生成とStudio編集を中心にする。", "動画制作では生成音声、環境音、音楽を別工程として組み合わせる。"],
    keyWords: [{ term: "TTS", meaning: "Text-to-Speech。文章を発話音声へ変える" }, { term: "Voice cloning", meaning: "少量の音声から声の特徴を再現する" }, { term: "Stem", meaning: "ボーカルやドラムなど分離した音源" }],
    explainPrompt: "ElevenLabsとSunoを、どちらも『音AI』で終わらせず違いを説明してください。",
    ownWords: ["声と曲は別タスク", "生成後の編集単位が重要", "同意・権利・商用条件を確認"],
    newsTerms: ["text to speech", "voice cloning", "music generation", "Suno", "ElevenLabs", "dubbing"],
    prerequisites: [5, 15],
    references: [{ label: "ElevenLabs Models", url: "https://elevenlabs.io/docs/overview/models", note: "音声モデルの公式一覧" }, { label: "Suno Blog", url: "https://about.suno.com/blog", note: "Studioや音楽制作機能の公式発表" }],
  },
  19: {
    todaysIdea: "APIは、別のソフトからAI機能へ決まった形式で依頼する窓口。",
    whyExists: "人が画面を操作するだけでなく、アプリや自動処理からモデルを再現可能な形で使うため。",
    howUsed: "Requestに入力・モデル・設定を送り、Responseの文章・画像・構造化データをアプリが受け取る。",
    whyCare: "API Key、料金、Rate limit、失敗時Retry、ログ、個人情報を設計しないと、動くデモが安全な製品にならない。",
    realExamples: ["Briefがニュース候補をAI APIへ送り、日本語解説を構造化して受け取る。", "Social DeskがSNS APIへ投稿データを送る。"],
    keyWords: [{ term: "API", meaning: "ソフトウェア同士が決まった形式で機能を呼ぶ窓口" }, { term: "Request", meaning: "APIへ送る依頼" }, { term: "Response", meaning: "APIから返る結果" }, { term: "API Key", meaning: "呼び出し元を認証する秘密情報" }],
    explainPrompt: "Chat画面でAIを使う場合と、APIでアプリへ組み込む場合の違いは？",
    ownWords: ["ソフト同士の窓口", "決まった形式で送受信", "認証・費用・失敗処理も必要"],
    newsTerms: ["API", "developer platform", "rate limit", "SDK"],
    prerequisites: [6, 11, 13],
  },
  20: {
    todaysIdea: "Tool UseはAIが外部機能を選ぶ仕組み、Function Callingはその呼び出し情報を構造化する方法。",
    whyExists: "LLMに計算、検索、送信、保存を文章で真似させず、実際のソフトへ安全に任せるため。",
    howUsed: "モデルがTool名と引数を返し、アプリが実行し、その結果を再びモデルへ渡して最終回答を作る。",
    whyCare: "AIがToolを選ぶことと、実行権限を持つことは別。引数検証、最小権限、確認画面が必要。",
    realExamples: ["天気Toolへ都市名を渡し、実データを取得して回答する。", "投稿Toolは下書きまで自動、公開だけ人の承認にできる。"],
    keyWords: [{ term: "Tool Use", meaning: "モデルが外部機能を選択して利用する仕組み" }, { term: "Function Calling", meaning: "Tool名と引数を機械可読な形で返す方法" }, { term: "Structured Output", meaning: "JSONなど決めた構造に沿う出力" }],
    explainPrompt: "LLMに『メールを送ったふり』をさせず、本当に送るまでの流れを説明してください。",
    ownWords: ["モデルはToolを選ぶ", "アプリが検証して実行", "結果を戻して次を決める"],
    newsTerms: ["tool use", "function calling", "structured output", "computer use"],
    prerequisites: [12, 13, 19],
  },
  21: {
    todaysIdea: "RAGは、回答前に外部資料を検索し、その根拠をContextへ追加する構成。",
    whyExists: "モデルを再学習せず、最新情報・社内資料・自分のデータを根拠に回答させるため。",
    howUsed: "資料をChunkへ分けてEmbedding化し、質問に近い部分をVector Databaseから取り出してLLMへ渡す。",
    whyCare: "RAGの失敗はモデルの頭の悪さとは限らない。資料不足、分割、検索、順位、引用設計を順に調べる。",
    realExamples: ["社内規程から休暇ルールを検索して回答する。", "Briefはまず実在記事やPubMed抄録を取得し、その内容を要約する。"],
    keyWords: [{ term: "RAG", meaning: "Retrieval-Augmented Generation。検索で根拠を足して生成する構成" }, { term: "Retrieval", meaning: "必要な資料を取り出す処理" }, { term: "Chunk", meaning: "検索しやすい大きさへ分けた資料の単位" }],
    explainPrompt: "RAGとFine-tuningを混同している人へ、『最新社内資料』を例に違いを説明してください。",
    ownWords: ["先に外部資料を検索", "根拠をContextへ入れる", "再学習なしで更新しやすい"],
    newsTerms: ["RAG", "retrieval augmented generation", "enterprise search", "grounding"],
    prerequisites: [9, 10, 12, 19],
  },
  22: {
    todaysIdea: "AI Agentは、目的に向けて観察・判断・Tool実行・確認を繰り返すシステム。",
    whyExists: "一回答えるだけでなく、途中結果に応じて複数の操作を選び直し、仕事を完了するため。",
    howUsed: "計画し、検索やブラウザ・コード・業務APIを使い、結果を見て次の手順を決め、停止条件まで進む。",
    whyCare: "『自律型』という言葉より、使えるTool、権限、状態保存、失敗時の停止、人の承認を見る。",
    realExamples: ["調査Agentが検索→一次情報確認→比較→出典付き報告まで進める。", "制作Agentが素材整理や案出しを行い、公開前に人へ確認する。"],
    keyWords: [{ term: "AI Agent", meaning: "目的に向けて複数回判断・行動するAIシステム" }, { term: "Loop", meaning: "観察・判断・実行・確認の繰り返し" }, { term: "State", meaning: "途中経過や現在位置の記録" }],
    explainPrompt: "通常のChatbotとAI Agentの違いを、ToolとLoopを使って説明してください。",
    ownWords: ["目的へ複数手順で進む", "Tool結果を見て次を変える", "権限と停止条件が重要"],
    newsTerms: ["AI agent", "agentic", "computer use", "workflow agent"],
    prerequisites: [14, 19, 20],
  },
  23: {
    todaysIdea: "MCPは、AIアプリとデータ・Toolの接続方法をそろえるためのProtocol。",
    whyExists: "AI製品ごとに同じ外部連携を個別実装する重複を減らし、発見・呼び出し方法を標準化するため。",
    howUsed: "Host内のMCP ClientがServerからToolやResourceを見つけ、利用者の権限内で呼び出す。",
    whyCare: "MCP対応だけでは安全とは限らない。接続先の信頼性、権限、入力内容、実行前確認は別途必要。",
    realExamples: ["一つのファイル接続Serverを複数の対応AIクライアントから使う。", "社内DBをResource、更新操作をToolとして分ける。"],
    keyWords: [{ term: "MCP", meaning: "Model Context Protocol。AIと外部機能の接続規格" }, { term: "Host", meaning: "AI体験を提供するアプリ" }, { term: "Client", meaning: "Host内でMCP接続を管理する部分" }, { term: "Server", meaning: "ToolやResourceを提供する側" }],
    explainPrompt: "MCPを『AIそのもの』ではなく接続規格として説明してください。",
    ownWords: ["AIと外部機能の共通接続", "Host・Client・Serverに分かれる", "権限管理は別に必要"],
    newsTerms: ["MCP", "Model Context Protocol", "MCP server"],
    prerequisites: [19, 20, 22],
    references: [{ label: "Model Context Protocol", url: "https://modelcontextprotocol.io/docs/getting-started/intro", note: "概念と構成要素の公式解説" }],
  },
  24: {
    todaysIdea: "AIのMemoryは、会話履歴、要約、プロフィール、検索可能ログなど複数の保存方法の総称。",
    whyExists: "Context Windowの外でも好みや作業途中を引き継ぎ、毎回ゼロから説明する負担を減らすため。",
    howUsed: "短期履歴はContextへ、長期情報はDBへ保存し、必要な時だけ検索して戻す。",
    whyCare: "何を覚え、誰が見られ、いつ消せるかが重要。誤った記憶の訂正と機密情報の除外も設計する。",
    realExamples: ["文章の好みをプロフィールとして保存する。", "Agentの途中状態を保存し、後から同じ手順を再開する。"],
    keyWords: [{ term: "Short-term memory", meaning: "現在の会話Contextにある一時的情報" }, { term: "Long-term memory", meaning: "会話を越えて保存される情報" }, { term: "State", meaning: "未完了作業の現在位置" }],
    explainPrompt: "『AIが覚えている』を、Contextと長期保存に分けて説明してください。",
    ownWords: ["Memoryは一種類ではない", "必要情報だけContextへ戻す", "確認・訂正・削除が必要"],
    newsTerms: ["AI memory", "personalization", "persistent memory", "stateful agent"],
    prerequisites: [9, 10, 21, 22],
  },
  25: {
    todaysIdea: "Fine-tuningは、特定の振る舞いを安定させるために学習済みモデルを追加Trainingする方法。",
    whyExists: "Promptだけでは安定しない形式・語調・判断パターンを、多数の良い例からモデルへ調整するため。",
    howUsed: "入出力例を用意し、用途特有の形式や分類、ブランド文体などを繰り返し学習させる。",
    whyCare: "最新情報を覚えさせる第一選択とは限らない。知識更新はRAG、振る舞い調整はFine-tuningと考えると整理しやすい。",
    realExamples: ["大量の社内分類例に合わせて出力ラベルを安定させる。", "毎日変わる価格表の参照には再学習よりRAGが向く。"],
    keyWords: [{ term: "Fine-tuning", meaning: "学習済みモデルへの追加Training" }, { term: "Dataset", meaning: "追加学習に使う例の集合" }, { term: "Post-training", meaning: "基礎学習後に行う調整工程の総称" }],
    explainPrompt: "RAGとFine-tuningを、『知識』と『振る舞い』の違いから説明してください。",
    ownWords: ["追加学習で振る舞いを調整", "良い例の質が重要", "最新知識ならまずRAGを検討"],
    newsTerms: ["fine-tuning", "post-training", "reinforcement learning", "custom model"],
    prerequisites: [4, 13, 21],
  },
  26: {
    todaysIdea: "Local AIは自分の機器で動かす方式、Open Weightは学習済みWeightが配布されるモデル。",
    whyExists: "プライバシー、遅延、オフライン、費用、独自改変などクラウドAPIでは満たしにくい条件へ対応するため。",
    howUsed: "配布WeightをGPUや端末へ置き、量子化などで必要メモリを減らしてInferenceする。",
    whyCare: "Open Weightと完全なOpen Sourceは同義ではない。License、学習データ開示、商用条件、必要Hardwareを確認する。",
    realExamples: ["Meta Llama系など配布Weightを対応環境で動かす。", "機密文書を外へ送らず、端末内の小型モデルで分類する。"],
    keyWords: [{ term: "Local AI", meaning: "手元や自社環境でモデルを動かす方式" }, { term: "Open Weight", meaning: "学習済みParameterが入手できるモデル" }, { term: "Quantization", meaning: "数値精度を下げて容量・計算を軽くする方法" }],
    explainPrompt: "Open WeightとOpen Sourceを同じと言い切れない理由は？",
    ownWords: ["実行場所と公開範囲は別", "Weightが入手できる", "Licenseと必要Hardwareを確認"],
    newsTerms: ["open-weight model", "open source AI", "local LLM", "quantization", "Llama"],
    prerequisites: [3, 11, 19],
    references: [{ label: "Meta Llama", url: "https://www.llama.com/", note: "配布モデルと利用条件の公式入口" }],
  },
  27: {
    todaysIdea: "Benchmarkは共通テスト、Evalは用途に合う基準でAIシステムを測る工程。",
    whyExists: "『賢そう』という印象では変更の良し悪しや失敗の再発を判断できないため。",
    howUsed: "典型例・難例・過去失敗を固定し、正確さ、完遂率、速度、費用、安全性を変更前後で比べる。",
    whyCare: "公開Benchmarkの首位が自分の制作や業務で最良とは限らない。試したい実タスクのEvalを持つ方が強い。",
    realExamples: ["画像モデルを画質だけでなく人物一貫性と修正回数で比較する。", "Briefの重要度判定を、人が付けた過去ラベルと比較する。"],
    keyWords: [{ term: "Benchmark", meaning: "モデル間を共通条件で比べる試験" }, { term: "Eval", meaning: "用途に合う基準で品質を測る評価" }, { term: "Rubric", meaning: "採点観点と水準を定めた基準表" }, { term: "Regression", meaning: "変更で以前できたことが悪化すること" }],
    explainPrompt: "Benchmark一位のモデルをそのまま採用しない理由を説明してください。",
    ownWords: ["共通試験と自分用評価は別", "品質・速度・費用・安全を測る", "変更前後を同じ例で比べる"],
    newsTerms: ["benchmark", "eval", "leaderboard", "human preference", "task completion"],
    prerequisites: [4, 11, 12],
  },
  28: {
    todaysIdea: "AIの安全性は、モデル精度だけでなくデータ、権利、権限、公開後の運用まで含む。",
    whyExists: "AIが外部データやToolへ接続すると、誤情報だけでなく漏洩、権利侵害、誤操作の被害が現実に起きるため。",
    howUsed: "入力データ制限、来歴表示、最小権限、承認、監査ログ、Red team、規約・法令確認を重ねる。",
    whyCare: "商用制作では学習データ論点、生成物の類似・肖像・商標、各サービスの契約条件を別々に確認する。法的扱いは地域と時期で変わる。",
    realExamples: ["Web内の命令文にAgentが従うPrompt Injectionを、外部データ扱いと権限制限で防ぐ。", "EU AI Actでは段階的適用が進むため、提供地域と役割に応じた最新確認が必要。"],
    keyWords: [{ term: "Training data", meaning: "モデル学習に使われるデータ" }, { term: "Prompt Injection", meaning: "外部データを悪意ある命令として読ませる攻撃" }, { term: "Provenance", meaning: "素材や生成・編集過程の来歴" }, { term: "AI regulation", meaning: "AIの開発・提供・利用を扱う法規制" }],
    explainPrompt: "『AIで生成できたから商用利用も安全』と言い切れない理由を三つに分けてください。",
    ownWords: ["技術的可能と利用可能は別", "法・契約・権利を分ける", "Agentは最小権限と承認"],
    newsTerms: ["AI safety", "copyright", "training data", "AI Act", "regulation", "provenance"],
    prerequisites: [12, 20, 22],
    references: [{ label: "EU AI Act", url: "https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai", note: "適用時期と義務はEU公式情報で更新確認" }, { label: "文化庁 AIと著作権", url: "https://www.bunka.go.jp/seisaku/chosakuken/aiandcopyright.html", note: "日本の論点整理への公式入口" }],
  },
  29: {
    todaysIdea: "主要企業の違いは、モデル名だけでなく、得意領域・製品・配布経路・事業基盤で見る。",
    whyExists: "同じ『高性能AI』でも、研究、Cloud、Office、SNS、半導体、制作Toolなど勝ち筋が異なるため。",
    howUsed: "OpenAI、Google DeepMind、Anthropic、xAI、Meta、Microsoft、NVIDIAと、制作系各社を一枚の地図として比較する。",
    whyCare: "新モデル発表を読むとき、誰が・どの利用者へ・どの製品経路で・何を更新したかを説明できる。",
    realExamples: ["OpenAIは汎用モデルとAgent製品、GoogleはGeminiと検索・Workspace・Cloud、AnthropicはClaudeと企業・開発用途を展開。", "MetaはOpen WeightのLlama、MicrosoftはCopilot/Azureと業務配布、NVIDIAはGPUと開発基盤で層が異なる。", "Midjourney、Adobe、Runway、ByteDance、Kuaishou、MiniMax、Suno、ElevenLabsは制作工程ごとの強みを競う。"],
    keyWords: [{ term: "Frontier model", meaning: "その時点の最先端能力を狙う大規模モデル" }, { term: "Platform", meaning: "モデル、API、Tool、配布先をまとめた利用基盤" }, { term: "Distribution", meaning: "利用者へ製品を届ける経路" }, { term: "Model family", meaning: "速度や能力の異なる同系列モデル群" }],
    explainPrompt: "OpenAI、Google、Anthropicの違いを、単純な優劣ではなく事業と製品の軸で説明してください。",
    ownWords: ["各社はモデル以外の強みが違う", "研究・製品・Cloud・配布先を見る", "一つのBenchmarkで勝者を決めない"],
    newsTerms: ["OpenAI", "Google DeepMind", "Gemini", "Anthropic", "Claude", "xAI", "Grok", "Meta AI", "Llama", "Microsoft", "NVIDIA"],
    prerequisites: [6, 15, 19, 22, 26, 27],
    references: [{ label: "OpenAI News", url: "https://openai.com/news/", note: "モデル・製品の公式発表" }, { label: "Google Gemini Models", url: "https://ai.google.dev/gemini-api/docs/models", note: "現行モデルの公式一覧" }, { label: "Anthropic News", url: "https://www.anthropic.com/news", note: "Claudeの公式発表" }, { label: "xAI News", url: "https://x.ai/news", note: "Grokの公式発表" }],
  },
  30: {
    todaysIdea: "2026年の潮流は、モデル単体の点数から、実行・制作・接続・運用を含むシステム競争へ。",
    whyExists: "高性能モデルが増え、実用上の差がTool実行、Multimodal編集、速度、費用、権利、配布先にも広がったため。",
    howUsed: "複数モデルをRoutingし、RAG・Memory・Agent・MCPを組み合わせ、制作や業務の最後までつなぐ。",
    whyCare: "ニュースを『何が更新されたか／従来と何が違うか／誰の工程が変わるか／根拠は何か』の四問で自力整理できる。",
    realExamples: ["Agentは回答からブラウザ・PC・業務Toolを使う完遂能力へ競争軸を移す。", "画像・動画・音声は一発生成から参照一貫性、編集、複数モデルをまたぐWorkflowへ進む。", "小型高速モデルと大型ReasoningモデルのRouting、Open WeightとLocal実行、法規制・来歴管理が同時に重要になる。"],
    keyWords: [{ term: "Agentic workflow", meaning: "AIがToolを使い複数工程を進める仕事の流れ" }, { term: "Model routing", meaning: "仕事に合わせて複数モデルを使い分けること" }, { term: "Creative workflow", meaning: "生成から編集・書き出しまでの制作工程" }, { term: "Governance", meaning: "権限・規則・監査を含む運用管理" }],
    explainPrompt: "今日見たAIニュースを一つ選び、『何が起きた／何が違う／なぜ重要／誰に影響』で30秒説明してください。",
    ownWords: ["モデル名より変化の軸を見る", "実行・編集・接続までが競争", "一次情報と実利用の評価で判断", "分からない点は分からないと区切る"],
    newsTerms: ["agentic workflow", "multimodal creation", "model routing", "open-weight", "AI governance", "robotics", "GPU"],
    prerequisites: [22, 23, 27, 28, 29],
    references: [{ label: "Microsoft Build 2026", url: "https://blogs.microsoft.com/blog/2026/06/02/microsoft-build-2026-be-yourself-at-work/", note: "Agentと業務システム統合の公式発表" }, { label: "Adobe Firefly 2026", url: "https://blog.adobe.com/en/publish/2026/06/18/adobe-firefly-introduces-new-agentic-capabilities-and-an-upgraded-creative-ai-studio-built-for-the-way-you-work", note: "制作Workflowの公式発表" }, { label: "Runway Media Router", url: "https://runwayml.com/news/company-news/introducing-runway-media-router", note: "複数生成モデルを制作工程で選ぶ例" }],
  },
};
