import type { MusicTrack } from "./MusicGrid";

export const navigation = [
  ["TOP", "/#top"], ["GALLERY", "/#gallery"], ["MUSIC", "/#music"], ["SHOP", "/#shop"], ["PROFILE", "/#profile"], ["NEWS", "/#news"], ["JOURNAL", "/#journal"], ["LINK", "/#link"], ["CONTACT", "/#contact"],
] as const;

export const galleryItems = [
  { src: "/gallery/gallery-48.webp", alt: "暗い森を背景に拳銃をこちらへ向ける白髪の天使を描いた青灰色のAIイラスト" },
  { src: "/gallery/gallery-39.webp", alt: "青と橙の抽象的な風景に立つ黒髪の少女を描いたAIイラスト作品" },
  { src: "/gallery/gallery-40.webp", alt: "屋外の光の中で座る緑色の瞳の白髪天使を描いた生成AIアート" },
  { src: "/gallery/gallery-41.webp", alt: "階段の影に佇む黒いドレスの白髪少女を描いた幻想的なAIイラスト" },
  { src: "/gallery/gallery-42.webp", alt: "月のタトゥーと白いドレスをまとった緑色の瞳の白髪少女のAIアート" },
  { src: "/gallery/gallery-43.webp", alt: "白い背景で横顔を見せる黒髪の少女を描いた繊細な線画風AIイラスト" },
  { src: "/gallery/gallery-44.webp", alt: "黒いリボンを付けた白髪の少女を都市の抽象表現で描いたAIアート" },
  { src: "/gallery/gallery-45.webp", alt: "灰色のTシャツとチェック柄スカートを着た黒髪少女の生成AIイラスト" },
  { src: "/gallery/gallery-46.webp", alt: "都市の路地で白い薔薇を持つ黒髪の天使を描いた幻想的なAIアート" },
  { src: "/gallery/gallery-47.webp", alt: "夜の森で光る十字架を持つ白髪の天使を描いた青色調のAIイラスト" },
  { src: "/gallery/gallery-19.webp", alt: "WS studioの生成AIアート作品 gallery 19" },
  { src: "/gallery/gallery-20.webp", alt: "WS studioの生成AIアート作品 gallery 20" },
  { src: "/gallery/gallery-21.webp", alt: "WS studioの生成AIアート作品 gallery 21" },
  { src: "/gallery/gallery-22.webp", alt: "WS studioの生成AIアート作品 gallery 22" },
  { src: "/gallery/gallery-23.webp", alt: "WS studioの生成AIアート作品 gallery 23" },
  { src: "/gallery/gallery-24.webp", alt: "WS studioの生成AIアート作品 gallery 24" },
  { src: "/gallery/gallery-25.webp", alt: "WS studioの生成AIアート作品 gallery 25" },
  { src: "/gallery/gallery-26.webp", alt: "WS studioの生成AIアート作品 gallery 26" },
  { src: "/gallery/gallery-27.webp", alt: "WS studioの生成AIアート作品 gallery 27" },
  { src: "/gallery/gallery-28.webp", alt: "WS studioの生成AIアート作品 gallery 28" },
  { src: "/gallery/gallery-29.webp", alt: "WS studioの生成AIアート作品 gallery 29" },
  { src: "/gallery/gallery-30.webp", alt: "WS studioの生成AIアート作品 gallery 30" },
  { src: "/gallery/gallery-31.webp", alt: "WS studioの生成AIアート作品 gallery 31" },
  { src: "/gallery/gallery-32.webp", alt: "WS studioの生成AIアート作品 gallery 32" },
  { src: "/gallery/gallery-33.webp", alt: "WS studioの生成AIアート作品 gallery 33" },
  { src: "/gallery/gallery-34.webp", alt: "WS studioの生成AIアート作品 gallery 34" },
  { src: "/gallery/gallery-35.webp", alt: "WS studioの生成AIアート作品 gallery 35" },
  { src: "/gallery/gallery-36.webp", alt: "WS studioの生成AIアート作品 gallery 36" },
  { src: "/gallery/gallery-37.webp", alt: "WS studioの生成AIアート作品 gallery 37" },
  { src: "/gallery/gallery-38.webp", alt: "WS studioの生成AIアート作品 gallery 38" },
  { src: "/gallery/gallery-13.webp", alt: "白髪の天使が都市を背景に黒い薔薇を持つAIイラスト作品" },
  { src: "/gallery/gallery-14.webp", alt: "透明感のある青白い光に包まれた白髪の天使のAI画像作品" },
  { src: "/gallery/gallery-15.webp", alt: "緑色の瞳の白髪少女が黒い薔薇を持つAIアート作品" },
  { src: "/gallery/gallery-16.webp", alt: "森の木の枝に座る白髪の天使を描いた生成AIイラスト" },
  { src: "/gallery/gallery-17.webp", alt: "夜にヘッドホンを着けテディベアを持つ少女のAIイラスト" },
  { src: "/gallery/gallery-18.webp", alt: "冷たい青色の光に包まれた天使の幻想的なAIアート" },
  { src: "/gallery/gallery-07.webp", alt: "青い水辺に座る白髪の天使を描いたAI画像作品" },
  { src: "/gallery/gallery-08.webp", alt: "ローアングルから見上げた白髪の天使のAIイラスト作品" },
  { src: "/gallery/gallery-09.webp", alt: "装飾的な白いドレスを着た白髪の天使のAIアート" },
  { src: "/gallery/gallery-10.webp", alt: "柔らかな青い光の中で髪を結ぶ天使の生成AIイラスト" },
  { src: "/gallery/gallery-11.webp", alt: "陽光の中でブランコに座る天使を描いたAI画像作品" },
  { src: "/gallery/gallery-12.webp", alt: "青と橙の木々に囲まれた白髪の天使のAIアート作品" },
  { src: "/gallery/gallery-01.webp", alt: "リンゴを手に持つ白髪の天使を描いたAIイラスト" },
  { src: "/gallery/gallery-02.webp", alt: "青と金色の植物に囲まれた白髪の天使のAI画像" },
  { src: "/gallery/gallery-03.webp", alt: "光る球体へ手を伸ばす白髪の天使の幻想的なAIアート" },
  { src: "/gallery/gallery-04.webp", alt: "朝の柔らかな光の中で花を持つ天使のAIイラスト" },
  { src: "/gallery/gallery-05.webp", alt: "夜の都市と月を背景にした少女の生成AI画像作品" },
  { src: "/gallery/gallery-06.webp", alt: "ブルーアワーの踏切に立つ少女を描いたAIイラスト作品" },
] as const;

export const musicTracks: MusicTrack[] = [
  { title: "Marry Me? (feat. おchillちゃん)", artwork: "/music/marry-me.jpg", spotifyUrl: "https://open.spotify.com/track/1wqFSMqLQB9ArZ7AMNqDxo", previewUrl: "https://p.scdn.co/mp3-preview/1f9180287bbfe578baebc36c5d8aaac29b5656f7" },
  { title: "夜中、3時半に、また (feat. おchillちゃん)", artwork: "/music/marry-me.jpg", spotifyUrl: "https://open.spotify.com/track/4k3gRshbHLKbx8xGX9WfZn", previewUrl: "https://p.scdn.co/mp3-preview/9bf5d0f39a06a87ba082bf502c66c6490cd807ec" },
  { title: "Today, I smiled. (feat. Rin)", artwork: "/music/today-i-smiled.jpg", spotifyUrl: "https://open.spotify.com/track/6Am8QCT72RHW1rFEr4QmmE", previewUrl: "https://p.scdn.co/mp3-preview/b437b632b7065aa765a9ef7d0cd6e5e5c17de656" },
  { title: "Keep me running (feat. Rin)", artwork: "/music/today-i-smiled.jpg", spotifyUrl: "https://open.spotify.com/track/2dpp6kRYICU4VdtXCEzH8r", previewUrl: "https://p.scdn.co/mp3-preview/f054288f2b04c4edaf6434509400e1185db64a74" },
  { title: "Sweater Weather Girl (feat. Rin)", artwork: "/music/today-i-smiled.jpg", spotifyUrl: "https://open.spotify.com/track/47nZ3zEJPMGoRWGBqfA2N8", previewUrl: "https://p.scdn.co/mp3-preview/16a1e38b3df93da880fc5b8b572d73d3f9762dcb" },
  { title: "SNS jellyfish (feat. Rin)", artwork: "/music/today-i-smiled.jpg", spotifyUrl: "https://open.spotify.com/track/1CNzGUIEukxlfxTwquavET", previewUrl: "https://p.scdn.co/mp3-preview/8ac1e05b760b6f5caffb707767ffe42bf6c33c46" },
  { title: "Under the moon (feat. Rin)", artwork: "/music/today-i-smiled.jpg", spotifyUrl: "https://open.spotify.com/track/0eOOClDDqxTimkb2jptbIG", previewUrl: "https://p.scdn.co/mp3-preview/d04fd1b54932b11c4354690d9056f0ac3a451e30" },
  { title: "私、天使なんだけど (feat. おchillちゃん)", artwork: "/music/watashi-tenshi.jpg", spotifyUrl: "https://open.spotify.com/track/6P0VwfjHBmEmYRZkzyc5dT", previewUrl: "https://p.scdn.co/mp3-preview/4b6babf0071ac4fc870e28846eea2f121988e9a9" },
  { title: "AIなんていらない", artwork: "/music/ai-nante-iranai.jpg", spotifyUrl: "https://open.spotify.com/track/4kLgABtDPMiFG0yvqL4sN6", previewUrl: "https://p.scdn.co/mp3-preview/bcd3a9aa2df94fb73826a7d2c623986712d279ea" },
  { title: "指についた星 — JAGA RECORDS mix", artwork: "/music/yubi-ni-tsuita-hoshi.jpg", spotifyUrl: "https://open.spotify.com/track/5dvmoAORWyvZyq6tIRFixJ", previewUrl: "https://p.scdn.co/mp3-preview/6b71be18b4bb711922c9be4376ac7edf94acfa09" },
  { title: "朝と海とレモンチューハイ (feat. おchillちゃん)", artwork: "/music/asa-umi-lemon.jpg", spotifyUrl: "https://open.spotify.com/track/2R6y0bROSl6wScPOjUM2Ku", previewUrl: "https://p.scdn.co/mp3-preview/f0d95ebcf596a99420814267caac488624c779ec" },
  { title: "ヘッドホンは宇宙船 (feat. おchillちゃん)", artwork: "/music/headphone-spaceship.jpg", spotifyUrl: "https://open.spotify.com/track/4lOsXg985ypaIIGliBnNzC", previewUrl: "https://p.scdn.co/mp3-preview/5d7d785964807378ad25858ec82bf468846677bf" },
];
